services:
  db:
    image: mipemo01/sqlpinacoteca:v1
    container_name: contenedorPinacotecaDB
    ports:
      - "3306:3306"
    networks:
      - mi-red

  app:
    image: mipemo01/phppinacoteca:v1
    container_name: contenedorPinacotecaApp
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge